Repository Anuka-R98/ITPM_PROJECT, pull requests merged in 2022-05, with the labels that each got.

#29 place order screen & order summery
  frontend/src/screens/PlaceOrderScreen.js
Labels: enhancement, idea

#48 Implemented product model.js
  backend/models/productModel.js
Labels: to develop

#62 Order list report generation
  frontend/src/screens/OrderListScreen.js
  frontend/src/screens/OrderListScreenS.js
Labels: enhancement
